fake_csv/urls.py
from django.urls import path

from fake_csv.views import (
    CreateSchemaView,
    UpdateSchemaView,
    SchemasListView,
    DatasetView,
    DeleteSchemaView,
    DeleteColumnView,
    GenerateFileView,
)

urlpatterns = [
    path("schema/create/", CreateSchemaView.as_view(), name="schema-create"),
    path("schema/<int:pk>/edit/", UpdateSchemaView.as_view(), name="schema-edit"),
    path("", SchemasListView.as_view(), name="schemas-list"),
    path("datasets/<int:pk>/", DatasetView.as_view(), name="datasets"),
    path(
        "schema/delete/schema/<int:pk>",
        DeleteSchemaView.as_view(),
        name="schema-delete",
    ),
    path(
        "schema/delete/column/<int:pk>",
        DeleteColumnView.as_view(),
        name="column-delete",
    ),
    path("datasets/<int:pk>/update/", GenerateFileView.as_view(), name="generate-file"),
]

app_name = "schemas"

fake_csv_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("fake_csv.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="container-fluid bg-light">
  <div class="row">
    <div class="col-1 py-2">
      <h4>FakeCSV</h4>
    </div>
    <div class="col-8 d-flex align-items-center">
      <h5><a href="{% url 'schemas:schemas-list' %}" class="text-dark text-decoration-none">Schemas</a></h5>
    </div>
    <div class="col-2 d-flex align-items-center justify-content-end">
      <span>Hello, {{ user.get_username }}</span>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="ms-3 text-dark">Logout</a>
      {% else %}
        <a href="{% url 'login'%}?next={{request.path}}" class="ms-3 text-dark">Log in</a>
      {% endif %}
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination align-items-center">
    {% if page_obj.has_previous %}
      <li class="page-item me-1"><a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">&lt;</a></li>
    {% endif %}
      <li><h5>{{ page_obj.number }} of {{ paginator.num_pages }}</h5></li>
    {% if page_obj.has_next %}
      <li class="page-item ms-1"><a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">&gt;</a></li>
    {% endif %}
  </ul>
{% endif %}