fake_csv/urls.py
from django.urls import path

from fake_csv.views import (
    CreateSchemaView,
    UpdateSchemaView,
    SchemasListView,
    DatasetView,
    DeleteSchemaView,
    DeleteColumnView,
    GenerateFileView,
)

urlpatterns = [
    path("schema/create/", CreateSchemaView.as_view(), name="schema-create"),
    path("schema/<int:pk>/edit/", UpdateSchemaView.as_view(), name="schema-edit"),
    path("", SchemasListView.as_view(), name="schemas-list"),
    path("datasets/<int:pk>/", DatasetView.as_view(), name="datasets"),
    path(
        "schema/delete/schema/<int:pk>",
        DeleteSchemaView.as_view(),
        name="schema-delete",
    ),
    path(
        "schema/delete/column/<int:pk>",
        DeleteColumnView.as_view(),
        name="column-delete",
    ),
    path("datasets/<int:pk>/update/", GenerateFileView.as_view(), name="generate-file"),
]

app_name = "schemas"

fake_csv_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("fake_csv.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fake_csv/models.py
import os

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models


class DataSchema(models.Model):
    COLUMN_SEPARATORS = ((",", "Comma (,)"), (";", "Semicolon (;)"))

    STRING_CHARACTER = (("“", "Double-quote (“)"), ("‘", "Apostrophes (‘)"))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    column_separator = models.CharField(choices=COLUMN_SEPARATORS, max_length=1)
    string_character = models.CharField(choices=STRING_CHARACTER, max_length=1)
    created_at = models.DateTimeField(auto_now_add=True)


class Column(models.Model):
    TYPES = (
        ("Full name", "Full name"),
        ("Job", "Job"),
        ("Email", "Email"),
        ("Domain name", "Domain name"),
        ("Phone number", "Phone number"),
        ("Company name", "Company name"),
        ("Text", "Text"),
        ("Integer", "Integer"),
        ("Address", "Address"),
        ("Date", "Date"),
    )
    schema = models.ForeignKey(
        DataSchema, on_delete=models.CASCADE, related_name="columns"
    )
    name = models.CharField(max_length=255)
    data_type = models.CharField(choices=TYPES, max_length=255)
    range_from = models.IntegerField(null=True, blank=True)
    range_to = models.IntegerField(null=True, blank=True)
    order = models.IntegerField()

    def clean(self):
        super().clean()
        if self.range_from and self.range_to and self.range_from > self.range_to:
            raise ValidationError(
                {"range_from": "Range from must be less than or equal to range to."}
            )


class DataSet(models.Model):
    schema = models.ForeignKey(
        DataSchema, on_delete=models.CASCADE, related_name="datasets"
    )
    rows = models.IntegerField()
    status = models.CharField(
        max_length=20,
        choices=(("Processing", "Processing"), ("Ready", "Ready")),
        default="PROCESSING",
    )
    file = models.FileField(upload_to=os.path.join("media/"), null=True)
    created_at = models.DateTimeField(auto_now_add=True)

fake_csv/forms.py
from django import forms

from .models import Column, DataSchema, DataSet


class SchemasForm(forms.ModelForm):
    class Meta:
        model = DataSchema
        fields = ["name", "column_separator", "string_character"]


class SchemasColumnForm(forms.ModelForm):
    class Meta:
        model = Column
        fields = ["name", "data_type", "range_from", "range_to", "order"]
        labels = {
            "range_from": "From",
            "range_to": "To",
        }


class DataschemaForm(forms.ModelForm):
    class Meta:
        model = DataSet
        fields = ["rows"]
        labels = {"rows": "Rows"}

fake_csv/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.forms import modelformset_factory
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from .forms import SchemasForm, SchemasColumnForm, DataschemaForm
from .models import Column, DataSchema, DataSet

from .utils import generate_csv


class CreateSchemaView(LoginRequiredMixin, CreateView):
    template_name = "fake_csv/schemas/schema_create.html"
    form_class = SchemasForm
    success_url = reverse_lazy("schemas:schemas-list")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["formset"] = modelformset_factory(
                Column, form=SchemasColumnForm, extra=0
            )(self.request.POST)
        else:
            data["formset"] = modelformset_factory(
                Column, form=SchemasColumnForm, extra=0
            )()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context["formset"]
        if all([formset.is_valid(), form.is_valid()]):
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            self.object.save()
            for form in formset:
                child = form.save(commit=False)
                child.schema = self.object
                child.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class UpdateSchemaView(LoginRequiredMixin, UpdateView):
    template_name = "fake_csv/schemas/schema_edit.html"
    form_class = SchemasForm
    success_url = reverse_lazy("schemas:schemas-list")

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        user = self.request.user
        return get_object_or_404(DataSchema, pk=pk, user=user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["formset"] = modelformset_factory(
                Column, form=SchemasColumnForm, extra=0
            )(self.request.POST, queryset=self.object.columns.all())
        else:
            context["formset"] = modelformset_factory(
                Column, form=SchemasColumnForm, extra=0
            )(queryset=self.object.columns.all())
            columns = self.object.columns.all()
            context["columns"] = [i for i in columns]
            context["nested"] = zip(context["formset"], context["columns"])
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context["formset"]
        if formset.is_valid():
            self.object = form.save(commit=False)
            self.object.save()
            for form in formset:
                child = form.save(commit=False)
                child.schema = self.object
                child.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class DeleteColumnView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        column = Column.objects.get(pk=pk)
        column.delete()
        return HttpResponse(status=200)


class SchemasListView(LoginRequiredMixin, ListView):
    model = DataSchema
    ordering = ["-created_at"]
    context_object_name = "schemas_list"
    template_name = "fake_csv/schemas/schemas_list.html"
    paginate_by = 5

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user.id)


class DeleteSchemaView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        schema = DataSchema.objects.get(pk=pk)
        schema.delete()
        return HttpResponse(status=200)


class DatasetView(LoginRequiredMixin, DetailView):
    model = DataSchema
    context_object_name = "schema"
    form_class = DataschemaForm
    template_name = "fake_csv/data_sets/dataset_detail.html"

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class()
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(request.POST)
        if form.is_valid():
            dataset = form.save(commit=False)
            dataset.schema = self.object
            dataset.save()
            created_at = datetime.fromisoformat(str(dataset.created_at))
            return JsonResponse(
                {
                    "id": dataset.pk,
                    "created_at": created_at.strftime("%B %d, %Y, %I:%M %p")
                    .replace(" 0", " ")
                    .replace("AM", "a.m.")
                    .replace("PM", "p.m."),
                    "status": dataset.status,
                }
            )
        else:
            context = self.get_context_data(object=self.object, form=form)
            return self.render_to_response(context)


class GenerateFileView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        dataset = DataSet.objects.get(pk=pk)
        with transaction.atomic():
            dataset.file = generate_csv(
                DataSchema.objects.get(pk=dataset.schema.pk), dataset.rows
            )
            dataset.status = "READY"
            dataset.save()
        return JsonResponse(
            {
                "id": dataset.pk,
                "status": dataset.status,
                "file_url": dataset.file.url
            }
        )

templates/fake_csv/schemas/schema_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

<div class="row">
  <form method="POST">
    {% csrf_token %}
    <h1>New schema</h1>
    <div class="schema-for d-flex align-items-lg-start">
      <div class="col-5">{{ form|crispy }}</div>
      <button type="submit" class="ms-auto btn-primary btn mb-3">submit</button>
    </div>
    <div>
      {% if formset %}
        <h1>Schema columns</h1>
        {{ formset.management_form }}
        <div id="column-form-list" class="form-group col-auto"></div>
        <div class="card-body">
          <div id="empty-column-form" class="hidden" style="display: none">
            {{ formset.empty_form|crispy }}
            <button id="remove-column-btn" class="ps-3 pt-3 text-decoration-none text-danger btn btn-link">Delete</button>
          </div>
          <button id="add-column" type="button" class="btn-primary btn">Add column</button>
        </div>
    {% endif %}
    </div>
  </form>
</div>

<script>
  const add_column_btn = document.getElementById("add-column")
  const total_new_forms = document.getElementById("id_form-TOTAL_FORMS")
  add_column_btn.addEventListener("click", add_new_form)
  total_new_forms.setAttribute("value", "0")
  const total_old_forms = document.getElementById("id_form-INITIAL_FORMS")
  total_old_forms.setAttribute("value", "0")

  function add_new_form(event) {
    if (event) {
      event.preventDefault()
    }

    const current_column_forms = document.getElementsByClassName("new-column-form")
    let current_form_count = current_column_forms.length
    const column_form_copy = document.getElementById("column-form-list")
    const copy_empty_column_form = document.getElementById("empty-column-form").cloneNode(true)
    copy_empty_column_form.setAttribute("style", "")
    copy_empty_column_form.setAttribute("id", `form-${current_form_count}`)
    copy_empty_column_form.setAttribute("class", "new-column-form d-flex align-items-center")

    const regex = new RegExp("__prefix__", "g")
    copy_empty_column_form.innerHTML = copy_empty_column_form.innerHTML.replace(regex, current_form_count)
    total_new_forms.setAttribute("value", current_form_count + 1)
    const delete_column_btn = copy_empty_column_form.querySelector("#remove-column-btn")
    delete_column_btn.addEventListener("click", function(event) {
    event.preventDefault()
    copy_empty_column_form.remove()
    current_form_count = current_column_forms.length
    total_new_forms.setAttribute("value", current_form_count)
    })

    column_form_copy.append(copy_empty_column_form)

    const data_type_field = document.getElementById(`id_form-${current_form_count}-data_type`)
    const div_data_type_field = document.getElementById(`div_id_form-${current_form_count}-data_type`)
    const div_name_field = document.getElementById(`div_id_form-${current_form_count}-name`)
    const data_range_from_field = document.getElementById(`id_form-${current_form_count}-range_from`)
    const data_range_from_field_label = document.querySelector('label[for="id_form-' + current_form_count + '-range_from"]')
    const data_range_to_field = document.getElementById(`id_form-${current_form_count}-range_to`)
    const data_range_to_field_label = document.querySelector('label[for="id_form-' + current_form_count + '-range_to"]')
    const div_order_field = document.getElementById(`div_id_form-${current_form_count}-order`)
    const div_to_field = document.getElementById(`div_id_form-${current_form_count}-range_to`)
    const div_from_field = document.getElementById(`div_id_form-${current_form_count}-range_from`)
    data_range_from_field.setAttribute("style", "display: none")
    data_range_from_field_label.setAttribute("style", "display: none")
    data_range_to_field_label.setAttribute("style", "display: none")
    data_range_to_field.setAttribute("style", "display: none")
    div_data_type_field.setAttribute("class", "mb-3 p-3 col-3")
    div_order_field.setAttribute("class", "mb-3 col-2 ms-auto")
    div_name_field.setAttribute("class", "mb-3 pr-3 col-3")
    div_to_field.setAttribute("class", "mb-3 ms-3 col-1")
    div_from_field.setAttribute("class", "mb-3 col-1")

    data_type_field.addEventListener("change", add_range_fields)

    function add_range_fields(event) {
      if (event) {
        event.preventDefault()
      }
      if (data_type_field.options[data_type_field.selectedIndex].value === "Integer" || data_type_field.options[data_type_field.selectedIndex].value === "Text") {
        data_range_from_field.setAttribute("style", "")
        data_range_from_field_label.setAttribute("style", "")
        data_range_to_field_label.setAttribute("style", "")
        data_range_to_field.setAttribute("style", "")
      }
      else {
        data_range_from_field.setAttribute("style", "display: none")
        data_range_from_field_label.setAttribute("style", "display: none")
        data_range_to_field_label.setAttribute("style", "display: none")
        data_range_to_field.setAttribute("style", "display: none")
      }
    }
  }
</script>

{% endblock  %}

templates/fake_csv/schemas/schema_edit.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% csrf_token %}

{% block content %}

<div class="row">
  <form method="POST">
    {% csrf_token %}
    <h1>New schema</h1>
    <div class="schema-for d-flex align-items-lg-start">
      <div class="col-5">{{ form|crispy }}</div>
      <button type="submit" class="ms-auto btn-primary btn">submit</button>
    </div>
    {% if formset %}
      <h1>Schema columns</h1>
      {{ formset.management_form }}
      <div id="column-form-list" class="form-group col-auto">
          {% for form, column in nested %}
            <div class="column-form d-flex align-items-center">
              {{ form|crispy }}
            <a href="{% url 'schemas:column-delete' pk=column.id %}" class="delete-column-link mt-2 text-danger me-3 text-decoration-none">
              Delete
            </a>
            </div>
          {% endfor %}
      </div>
    <div id="empty-column-form" class="hidden" style="display: none">
      {{ formset.empty_form|crispy }}
      <button type="button" class="ps-3 pt-3 text-danger text-decoration-none btn btn-link" id="remove-column-btn">Delete</button>
    </div>
    <button id="add-column" type="button" class="btn-primary btn mb-3">Add column</button>
    {% endif %}
  </form>
</div>
<script>
    const add_column_btn = document.getElementById("add-column")
    const delete_column_btn = document.getElementById("remove-empty-column-btn")
    const total_new_forms = document.getElementById("id_form-TOTAL_FORMS")
    const total_old_forms = parseInt(document.getElementById("id_form-INITIAL_FORMS").value)
    const all_column_forms = document.getElementsByClassName("column-form")

    for (let i = 0; i < total_old_forms; i++) {
          const data_type_field = document.getElementById(`id_form-${i}-data_type`)
          const range_from_label = document.querySelector('label[for="id_form-' + i + '-range_from"]')
          const range_from_input = document.getElementById(`id_form-${i}-range_from`)
          const range_to_label = document.querySelector('label[for="id_form-' + i + '-range_to"]')
          const range_to_input = document.getElementById(`id_form-${i}-range_to`)

          const div_data_type_field = document.getElementById(`div_id_form-${i}-data_type`)
          const div_name_field = document.getElementById(`div_id_form-${i}-name`)
          const div_order_field = document.getElementById(`div_id_form-${i}-order`)
          const div_to_field = document.getElementById(`div_id_form-${i}-range_to`)
          const div_from_field = document.getElementById(`div_id_form-${i}-range_from`)

          div_data_type_field.setAttribute("class", "mb-3 p-3 col-3")
          div_order_field.setAttribute("class", "mb-3 col-2 ms-auto me-3")
          div_name_field.setAttribute("class", "mb-3 pr-3 col-3")
          div_to_field.setAttribute("class", "mb-3 ms-3 col-1")
          div_from_field.setAttribute("class", "mb-3 col-1")

          if (data_type_field.options[data_type_field.selectedIndex].value === "Integer" || data_type_field.options[data_type_field.selectedIndex].value === "Text") {
            range_from_input.setAttribute("style", "")
            range_from_label.setAttribute("style", "")
            range_to_label.setAttribute("style", "")
            range_to_input.setAttribute("style", "")
          }
          else {
            range_from_input.setAttribute("style", "display: none")
            range_from_label.setAttribute("style", "display: none")
            range_to_label.setAttribute("style", "display: none")
            range_to_input.setAttribute("style", "display: none")
          }
        data_type_field.addEventListener("change", add_range_fields)

        function add_range_fields(event) {
            if (event) {
                event.preventDefault()
            }
            if (data_type_field.options[data_type_field.selectedIndex].value === "Integer" || data_type_field.options[data_type_field.selectedIndex].value === "Text") {
              range_from_input.setAttribute("style", "")
              range_from_label.setAttribute("style", "")
              range_to_label.setAttribute("style", "")
              range_to_input.setAttribute("style", "")
            }
            else {
              range_from_input.setAttribute("style", "display: none")
              range_from_label.setAttribute("style", "display: none")
              range_to_label.setAttribute("style", "display: none")
              range_to_input.setAttribute("style", "display: none")
            }
        }
    }

    add_column_btn.addEventListener("click", add_new_form)

    function add_new_form(event) {
      if (event) {
          event.preventDefault()
      }

    const current_column_forms = document.getElementsByClassName("new-column-form")
    const current_form_count = current_column_forms.length + total_old_forms
    const column_form_copy = document.getElementById("column-form-list")
    const copy_empty_column_form = document.getElementById("empty-column-form").cloneNode(true)
    copy_empty_column_form.setAttribute("style", "")
    copy_empty_column_form.setAttribute("id", `form-${current_form_count}`)
    copy_empty_column_form.setAttribute("class", "new-column-form d-flex align-items-center")

    const regex = new RegExp("__prefix__", "g")
    copy_empty_column_form.innerHTML = copy_empty_column_form.innerHTML.replace(regex, current_form_count)
    total_new_forms.setAttribute("value", current_form_count + 1)
    const delete_column_btn = copy_empty_column_form.querySelector("#remove-column-btn")
      delete_column_btn.addEventListener("click", function(event) {
      event.preventDefault()
      copy_empty_column_form.remove()
      const total_old_forms = document.getElementsByClassName("column-form");
      const current_column_forms = document.getElementsByClassName("new-column-form")
      const current_form_count = current_column_forms.length + total_old_forms.length
      total_new_forms.setAttribute("value", current_form_count)
      })


    column_form_copy.append(copy_empty_column_form)

    const data_range_from_field = document.getElementById(`id_form-${current_form_count}-range_from`)
    data_range_from_field.setAttribute("style", "display: none")
    const data_range_from_label = `id_form-${current_form_count}-range_from`
    const data_range_from_field_label = document.querySelector('label[for="' + data_range_from_label + '"]')
    data_range_from_field_label.setAttribute("style", "display: none")
    const data_range_to_label = `id_form-${current_form_count}-range_to`
    const data_range_to_field = document.getElementById(`id_form-${current_form_count}-range_to`)
    const data_range_to_field_label = document.querySelector('label[for="' + data_range_to_label + '"]')
    data_range_to_field_label.setAttribute("style", "display: none")
    data_range_to_field.setAttribute("style", "display: none")

    const div_data_type_field = document.getElementById(`div_id_form-${current_form_count}-data_type`)
    const div_name_field = document.getElementById(`div_id_form-${current_form_count}-name`)
    const div_order_field = document.getElementById(`div_id_form-${current_form_count}-order`)
    const div_to_field = document.getElementById(`div_id_form-${current_form_count}-range_to`)
    const div_from_field = document.getElementById(`div_id_form-${current_form_count}-range_from`)

    div_data_type_field.setAttribute("class", "mb-3 p-3 col-3")
    div_order_field.setAttribute("class", "mb-3 col-2 ms-auto")
    div_name_field.setAttribute("class", "mb-3 pr-3 col-3")
    div_to_field.setAttribute("class", "mb-3 ms-3 col-1")
    div_from_field.setAttribute("class", "mb-3 col-1")


    const data_type_field = document.getElementById(`id_form-${current_form_count}-data_type`)
    data_type_field.addEventListener("change", add_range_fields)

    function add_range_fields(event) {
        if (event) {
            event.preventDefault()
        }
        if (data_type_field.options[data_type_field.selectedIndex].value === "Integer" || data_type_field.options[data_type_field.selectedIndex].value === "Text") {
          data_range_from_field.setAttribute("style", "")
          data_range_from_field_label.setAttribute("style", "")
          data_range_to_field_label.setAttribute("style", "")
          data_range_to_field.setAttribute("style", "")
        }
        else {
          data_range_from_field.setAttribute("style", "display: none")
          data_range_from_field_label.setAttribute("style", "display: none")
          data_range_to_field_label.setAttribute("style", "display: none")
          data_range_to_field.setAttribute("style", "display: none")
        }
    }
  }
  </script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(function() {
     $('.delete-column-link').click(function(event) {
       event.preventDefault();

       const deleteUrl = $(this).attr('href');

        $.ajaxSetup({
         data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
       });

      $.ajax({
        url: deleteUrl,
        type: 'POST',
        success: function(data) {
          $(event.target).closest('.column-form').remove();
          const total_old_forms = document.getElementsByClassName("column-form");
          const total_new_forms = document.getElementsByClassName("new-column-form");
          document.getElementById("id_form-TOTAL_FORMS").setAttribute("value", total_new_forms.length + total_old_forms.length);
          document.getElementById("id_form-INITIAL_FORMS").setAttribute("value", total_old_forms.length);
        }
      });
     });
   });
</script>

{% endblock  %}

templates/fake_csv/schemas/schemas_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% csrf_token %}

{% block content %}
  <div class="row">
    <h1 class="col">Data schemas</h1>
    <a href="{% url 'schemas:schema-create' %}" class="btn-success btn col-auto m-2">New schema</a>


  {% if schemas_list %}
    <table class="table table-bordered">
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Modified</th>
        <th>Actions</th>
      </tr>

      {% for schema in schemas_list %}
        <tr>
          <td class="fw-bold">
              {{ schema.id }}
          </td>
          <td>
              <a href="{% url 'schemas:datasets' pk=schema.id  %}">
                {{ schema.name }}
              </a>
          </td>
          <td>
              {{ schema.created_at }}
          </td>
          <td>
              <a class="update"
                href="{% url 'schemas:schema-edit' pk=schema.id %}">
                Edit scheme
              </a>
              <a href="{% url 'schemas:schema-delete' pk=schema.id %}" class="delete-schema-link text-danger ml-3">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
</div>
  {% else %}
      <p>There are no schema yet.</p>
  {% endif %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(function() {
     $('.delete-schema-link').click(function(event) {
       event.preventDefault();
       var deleteUrl = $(this).attr('href');

       $.ajaxSetup({
         data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
       });

       $.ajax({
         url: deleteUrl,
         type: 'POST',
         success: function(data) {
           $(event.target).closest('tr').remove();
         }
       });
     });
   });
</script>
{% endblock %}
{% block pagination %}
  {% include "includes/pagination.html" %}
{% endblock %}